### ISSUE TITLE
Be able to change the repositories location

### ISSUE THREAD

**Issue by poiuytrez** [smart-mobile-software/gitstack#32]

**Comment by imaffett** [comment]
I did this locally, but I had to modify a bunch of files (apache conf, python, javascript, etc).

I'd like to see this moved into a configuration area, or prompted at install so it can be kept with upgrades.

**Comment by poiuytrez** [comment]
I would like to have this feature in the configuration area. The main problem is that it is not possible to retrieve a directory path from a web browser for security reasons. 
The other solution is to add a new screen to the installer, but I don't really like it.

**Comment by imaffett** [comment]
The browser never needs to know the directory path.  It's all done server side.  

/gitstack/ uses django for the admin interface

/web/ uses PHP.  The problem is also the apache configuration files that need to be modified.  The only way this can be done efficiently is the installer.  I can't upgrade from 1.3 because of this reason.
