### ISSUE TITLE
[installer] the installer does not create a site directory

### ISSUE THREAD

**Issue by dodikk** [smart-mobile-software/gitstack#45]
I'm running a workstation with Windows7 Enterprise.
http://dl.dropbox.com/u/32947027/error-reports/1-work-windows.png

I've tried to install gitstack using the wizard. The installer has not created the "C:\inetpub\wwwroot\gitstack\" directory for a locally hosted gitstack site.
http://dl.dropbox.com/u/32947027/error-reports/gitstack-no-site.png

Note: I'm also hosting running Sitecore CMS on this workstation.

**Comment by poiuytrez** [comment]
GitStack runs by default under Apache on the port 80. It seems that you have IIS running on your workstation which is also using the port 80. 
What you should do is to modify the c:\gitstack\apache\config\httpd.conf file,
modify the line with 
Listen 80
to 
Listen 8080

Then restart the gitstack service.
You will be able to run gitstack using this url : 
http://localhost:8080/gitstack

**Comment by dodikk** [comment]
I have no "c:\gitstack\apache\config\" directory.
See "ls" output below.

It is "c:\gitstack\apache\conf"

**Comment by dodikk** [comment]
still 404
Is site content hosted in a "gitphp" directory?

Will moving it to "C:\inetpub\wwwroot\gitstack\" fix my issue?

**Comment by poiuytrez** [comment]
I meant  "c:\gitstack\apache\conf\httpd.conf", sorry.
Are you sure that you get an 404 when you are doing a http://localhost:8080/gitstack ?
Could you send me the screenshot of this 404 ? Is it a 404 from IIS or Apache ? 
Moving gitphp to C:\inetpub\wwwroot\gitstack\ will not fix your issue as this directory is releated to IIS.

**Comment by dodikk** [comment]
Yes. I'm pretty much sure. Anyway, I what I saw was not the login screen of gitstack.
You'll get a screenshot tomorrow ( 2012-04-06 ).
Not sure where it comes from.

Are IIS and Apache mutually exclusive? Should I really stop one of them to be able to run the other one?

**Comment by dodikk** [comment]
Today I've booted by computer and got gitstack web interface running.
I think you need to require reboot after components are installed.

**Comment by poiuytrez** [comment]
Hello Dodikk,

IIS and Apache are two webservers and their role is to listen to a specific port. They cannot listen to the same port. If they listen on the same port, only one webserver will reply to the request. By default, both webservers are running on the port 80. 
In this case, the first webserver which was run will reply to the request. On your computer, IIS was already running and that's why you got a 404 from IIS.
After your reboot, Apache seems to have started before IIS, so Apache replies to all requests on the port 80. I am almost sure that you sitecore website is not working anymore.

Apache and IIS are not mutually exclusive if they are not running on the same port. That's why I asked you earlier to change the Apache port to 8080.

We have to write a documentation note on how to run GitStack with other webservers to clarify the situation.

I will close #47 as there is not bug in the installer. The system does not need to reboot after a GitStack installation.

**Comment by dodikk** [comment]
Both apache and IIS are up and running at the moment.
Seems like the httpd.conf editing did not take any effect as both of us have forgotten to restart apache service. (So simple and so stupidly).

I agree, this is not a bug. However, you should think about including this case to your FAQ.

**Comment by dodikk** [comment]
http://gitstack.com/questions/fatal-inforefs-not-found/
re-Posted a question as suggested

**Comment by poiuytrez** [comment]
Great, I have replied.
