### ISSUE TITLE
Support hooks

### ISSUE THREAD

**Issue by poiuytrez** [smart-mobile-software/gitstack#56]

**Comment by Jopie64** [comment]
A Git pre-receive hook does not seem to be working. When the repo is pushed directly with msysgit 1.7.10, the hook is executed. When the repo is pushed via http via gitstack, the push is prevented by the hook and apache logs an error:

[Sun Apr 15 23:00:37 2012] [error] [client 127.0.0.1] error: cannot spawn hooks/pre-receive: No such file or directory

The pre-receive hook I'm testing with contains java-code which will access a svn repository outside the gitstack directory structure.

Here the complete context:
I was trying to use subgit ( http://subgit.com/ ) to build the synced git repository directly into the Gitstack repository directory. This works, except that all the repositories disappear from the gitstack repo administration page. This is because subgit uses jgit to build the git tree, and jgit formats its config files with indentations. The phyton datafile reader apparently does not support indentations in config files, so it can be worked around to remove the indentations in the git-config file. This is a different issue which is not a major problem because it can be easily worked around.

I was hoping that, when I commit to that gitstack repository via http, the subgit svn repository would automatically be synchronized. But that doesn't work because of the subgit pre-receive hook which somehow cannot be found...?
Apache error:
[Sun Apr 15 23:00:37 2012] [error] [client 127.0.0.1] error: cannot spawn hooks/pre-receive: No such file or directory

It however is executed when the same repo is pushed directly.

My guess is that this is an apache security issue because it needs to execute a script outside the usual execution place, and that script needs to execute subgits java code to access a svn repository outside the subgit directory structure alltogether. But I don't know enough about the apache architecture to know for sure...

**Comment by Jopie64** [comment]
I tested with an almost empty and an empty pre-receive hook. It turns out that the moment a repo gets a pre-receive hook, the commit fails with the above mentioned error. This ofcourse narrows the problem down because it has nothing to do with java instantiations or non-subdirectory access. On the client it goes like this:

E:\test\gitstack_test3>git push
Counting objects: 5, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 262 bytes, done.
Total 3 (delta 0), reused 0 (delta 0)
To http://Johan:xxxx@localhost/test3.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'http://Johan:xxxx@localhost/test3.git'

**Comment by Jopie64** [comment]
I investigated some more. Using sysinternals process monitor, I saw that it cannot find bash.exe when it tries to run the hook. A quick and dirty hack, adding the directory (in my case) E:\GitStack\git\bin to the global PATH environment variable, made the hook actually run! It now just does complain about /tmp not existing, but that is not as big an issue.

Is there a way to change the apache config so that this dirty hack is not needed?

**Comment by Jopie64** [comment]
Browsing the Internet, it seems not to be possible to change the PATH environment variable via apache config files. Actually, the dirty hack I did is recommended on this page:
http://jmodalwindow.java.net/manual/dpl/html/version.control.system.html#vcs.git.apache.config
In chapter 11.1.2. Git installation guide
They even have a solution about that error message for tmp, by just creating a directory, in my case, E:\GitStack\git\tmp.

Doing all this makes subgit actually work with GitStack which is great!! That's all I wanted.

**Comment by poiuytrez** [comment]
Thanks a lot for all your research ! That's great that we now know where is the issue :D.
