### ISSUE TITLE
User Names with spaces causing problems when using AD/LDAP 

### ISSUE THREAD

**Issue by pjbarry** [smart-mobile-software/gitstack#69]
While issue [#54](https://github.com/smart-mobile-software/gitstack/issues/54) states the Usernames are not allowed to contain spaces,  when using Active Directory configuration it is possible to add users to a repository that have spaces in their names if 'cn' is used as the 'Attribute' when setting up the configuration. This results in two users (e.g. first name and last name) being added to the repository user list, neither of which are valid usernames when cloning the repo.

**Comment by poiuytrez** [comment]
You are right. Thanks a lot for your reports.
After some investigation, I recommend to use "sAMAccountName" instead of "cn". It has no space. It is usually the logon username on Windows ( http://msdn.microsoft.com/en-us/library/windows/desktop/ms679635(v=vs.85).aspx ).
I will change it in the website documentation.
